// Trade Wind & Co. — production data
// Caribbean catamaran arbitrage brokerage. Inventory below is REAL: every
// boat is a currently-active listing on Moorings Brokerage, BVI Yacht Sales,
// or Just Catamarans as of May 2026. Photos hotlinked from each source's CDN.
//
// The scraper (scraper.js) refreshes data/scraped.js nightly with the latest
// candidate inventory from all four source brokers.

const SETTINGS = {
  brokerage: 'Trade Wind & Co.',
  entityType: 'Catamaran Import Service',
  tagline: 'Caribbean catamarans, duty-paid and delivered to your marina.',
  // The frictions that fund the spread — every one is a service line item.
  importDuty: 0.20,           // 20% — current US tariff rate on foreign-built vessels
  prepCost: 12000,            // pre-purchase survey + commissioning + cosmetic prep
  oceanDelivery: 11000,       // BVI → Florida ocean delivery
  customsRegistration: 3000,  // customs broker + USCG documentation
  marginTarget: 0.20,         // we list at landed cost × (1 + marginTarget)
  retailComp: 1.87,           // US-listed comparable cats retail at ~1.87× BVI ask (docs)
  // Per-deal soft costs deducted from gross margin to reach net
  cacPerDeal: 8000,
  legalPerDeal: 3500,
  transitReserve: 3500,
  capitalPerDeal: 0,
  escrowAgent: 'Yachtworld Escrow',
  // Regulatory
  license: 'Pending FL DBPR Yacht & Ship Broker License (FS 326)',
  // Contact
  domain: 'tradewindandco.com',
  phone: '(305) 555-0188',
  email: 'desk@tradewindandco.com',
  emailLeads: 'inquiries@tradewindandco.com',
  hq: 'Miami, Florida',
  address: '1450 Brickell Avenue, Suite 1900',
  cityStateZip: 'Miami, FL 33131',
  officeHours: 'Mon–Fri 9am–6pm EST · Sat by appointment',
  established: 2026,
  team: [
    { name: 'Brand Marshall', role: 'Founder · Sourcing & Strategy', bio: 'Twenty years of cross-border logistics. Builds the BVI sourcing pipeline and runs the marketing side.' },
    { name: 'Chris Halloway', role: 'Operations · Deal Execution', bio: 'Former rental-property operator. Runs the customer relationship from inspection through handover. FL Yacht & Ship Salesperson License pending.' },
    { name: 'Christian Reyes', role: 'General Counsel', bio: 'Commercial litigation attorney with insurance expertise. Drafts our contracts and reviews every transaction.' },
  ],
};

// ============================== Pricing math ==============================

function landedCost(boat, duty) {
  const d = duty ?? SETTINGS.importDuty;
  return boat.bviAsk + SETTINGS.prepCost + boat.bviAsk * d + SETTINGS.oceanDelivery + SETTINGS.customsRegistration;
}
function listPriceFor(boat, duty) {
  const raw = landedCost(boat, duty) * (1 + SETTINGS.marginTarget);
  return Math.round(raw / 5000) * 5000;
}
function grossMargin(boat, duty) {
  return listPriceFor(boat, duty) - landedCost(boat, duty);
}
function perDealCost() {
  return SETTINGS.cacPerDeal + SETTINGS.legalPerDeal + SETTINGS.transitReserve;
}
function netMargin(boat, duty) {
  return grossMargin(boat, duty) - perDealCost();
}
function buyerSavings(boat, duty) {
  return boat.usRetailComp - listPriceFor(boat, duty);
}

// ============================== Photos ==============================
// HERO photo — Sandy Spit, Jost Van Dyke, BVI. Wikimedia Commons, hotlink-OK.
const HERO_PHOTO = 'https://upload.wikimedia.org/wikipedia/commons/d/df/Sandy_Spit%2C_Jost_Van_Dyke.jpg';

// Placeholder for any boat that ever ends up with missing photos.
function photoUrl(label, view, w = 1200, h = 700) {
  const text = encodeURIComponent(`${label}\n— ${view} —`);
  return `https://placehold.co/${w}x${h}/1f6e72/f7f3eb?text=${text}&font=playfair`;
}

// ============================== Inventory (REAL listings) ==============================

const BOATS = [
  {
    id: 'leopard40-araume-iv',
    slug: 'araume-iv',
    category: '40ft',
    categoryLabel: '40 ft · 4-cabin',
    year: 2019,
    make: 'Leopard',
    model: '40',
    name: 'Araume IV',
    headline: 'Ex-Moorings owner-version 4-cabin — completed world-class refit at the St Lucia base.',
    loa: '39\' 4"',
    beam: '21\' 1"',
    draft: '4\' 1"',
    cabins: 4,
    heads: 2,
    berths: 8,
    engines: 'Twin Yanmar 3YM30 AE — 29 hp ea., Sail Drive SD20',
    engineHours: 2405,
    fuelGal: 95,
    waterGal: 206,
    sails: 'Main + jib (factory rig, well maintained)',
    electronics: 'Raymarine plotter · autopilot · standard Moorings nav suite',
    extras: 'Generator · A/C · 2-blade aluminum props · holding tank · post-refit cosmetics May 2026',
    originatingFleet: 'Moorings',
    phaseOutDate: '2025-04-15',
    bviAsk: 309000,
    usRetailComp: 555000,
    usComps: [
      { year: 2019, make: 'Leopard', model: '40', priceUSD: 535000, location: 'Fort Lauderdale, FL', source: 'YachtWorld', searchUrl: 'https://www.yachtworld.com/boats-for-sale/type-sail/class-catamaran/make-leopard/model-leopard-40/' },
      { year: 2019, make: 'Leopard', model: '40', priceUSD: 565000, location: 'Annapolis, MD', source: 'The Multihull Company', searchUrl: 'https://www.multihullcompany.com/sailboats-for-sale/' },
      { year: 2020, make: 'Leopard', model: '40', priceUSD: 589000, location: 'St. Petersburg, FL', source: 'Just Catamarans', searchUrl: 'https://justcatamarans.net/listings/' },
    ],
    location: { harbor: 'Road Town', country: 'Tortola, BVI', region: 'British Virgin Islands' },
    destinationPort: 'Fort Lauderdale, FL',
    inspectionWindows: ['Jun 3–10', 'Jun 24–Jul 1', 'Jul 22–29'],
    remoteVideoAvailable: true,
    sourceBroker: 'Moorings Brokerage',
    sourceListing: 'mooringsbrokerage.com #9681517',
    sourceUrl: 'https://www.mooringsbrokerage.com/used-boats/2019-leopard-40-virgin-islands-british-araume-iv-9681517',
    sourceListed: '2026-02-04',
    sourceLastChecked: '2026-05-18',
    sourcePriceHistory: [
      { date: '2026-02-04', price: 329000 },
      { date: '2026-04-02', price: 318000 },
      { date: '2026-05-08', price: 309000 },
    ],
    badge: 'Anchor Listing',
    status: 'available',
    daysActive: 103,
    leads: 14,
    inspections: 1,
    photos: [
      { url: 'photos/leopard40-araume-iv/1.jpg', label: 'At anchor, BVI' },
      { url: 'photos/leopard40-araume-iv/2.jpg', label: 'Cockpit & helm' },
      { url: 'photos/leopard40-araume-iv/3.jpg', label: 'Saloon & galley' },
      { url: 'photos/leopard40-araume-iv/4.jpg', label: 'Owner\'s cabin' },
      { url: 'photos/leopard40-araume-iv/5.jpg', label: 'View 5' },
      { url: 'photos/leopard40-araume-iv/6.jpg', label: 'View 6' },
      { url: 'photos/leopard40-araume-iv/7.jpg', label: 'View 7' },
      { url: 'photos/leopard40-araume-iv/8.jpg', label: 'View 8' },
      { url: 'photos/leopard40-araume-iv/9.jpg', label: 'View 9' },
      { url: 'photos/leopard40-araume-iv/10.jpg', label: 'View 10' },
      { url: 'photos/leopard40-araume-iv/11.jpg', label: 'View 11' },
      { url: 'photos/leopard40-araume-iv/12.jpg', label: 'View 12' },
      { url: 'photos/leopard40-araume-iv/13.jpg', label: 'View 13' },
      { url: 'photos/leopard40-araume-iv/14.jpg', label: 'View 14' },
      { url: 'photos/leopard40-araume-iv/15.jpg', label: 'View 15' },
      { url: 'photos/leopard40-araume-iv/16.jpg', label: 'View 16' },
      { url: 'photos/leopard40-araume-iv/17.jpg', label: 'View 17' },
      { url: 'photos/leopard40-araume-iv/18.jpg', label: 'View 18' },
      { url: 'photos/leopard40-araume-iv/19.jpg', label: 'View 19' },
      { url: 'photos/leopard40-araume-iv/20.jpg', label: 'View 20' },
      { url: 'photos/leopard40-araume-iv/21.jpg', label: 'View 21' },
      { url: 'photos/leopard40-araume-iv/22.jpg', label: 'View 22' },
      { url: 'photos/leopard40-araume-iv/23.jpg', label: 'View 23' },
      { url: 'photos/leopard40-araume-iv/24.jpg', label: 'View 24' },
      { url: 'photos/leopard40-araume-iv/25.jpg', label: 'View 25' },
      { url: 'photos/leopard40-araume-iv/26.jpg', label: 'View 26' },
      { url: 'photos/leopard40-araume-iv/27.jpg', label: 'View 27' },
      { url: 'photos/leopard40-araume-iv/28.jpg', label: 'View 28' },
      { url: 'photos/leopard40-araume-iv/29.jpg', label: 'View 29' },
      { url: 'photos/leopard40-araume-iv/30.jpg', label: 'View 30' },
      { url: 'photos/leopard40-araume-iv/31.jpg', label: 'View 31' },
      { url: 'photos/leopard40-araume-iv/32.jpg', label: 'View 32' },
      { url: 'photos/leopard40-araume-iv/33.jpg', label: 'View 33' },
      { url: 'photos/leopard40-araume-iv/34.jpg', label: 'View 34' },
      { url: 'photos/leopard40-araume-iv/35.jpg', label: 'View 35' },
      { url: 'photos/leopard40-araume-iv/36.jpg', label: 'View 36' },
      { url: 'photos/leopard40-araume-iv/37.jpg', label: 'View 37' },
      { url: 'photos/leopard40-araume-iv/38.jpg', label: 'View 38' },
      { url: 'photos/leopard40-araume-iv/39.jpg', label: 'View 39' },
      { url: 'photos/leopard40-araume-iv/40.jpg', label: 'View 40' },
      { url: 'photos/leopard40-araume-iv/41.jpg', label: 'View 41' },
      { url: 'photos/leopard40-araume-iv/42.jpg', label: 'View 42' },
      { url: 'photos/leopard40-araume-iv/43.jpg', label: 'View 43' },
      { url: 'photos/leopard40-araume-iv/44.jpg', label: 'View 44' },
      { url: 'photos/leopard40-araume-iv/45.jpg', label: 'View 45' },
      { url: 'photos/leopard40-araume-iv/46.jpg', label: 'View 46' },
      { url: 'photos/leopard40-araume-iv/47.jpg', label: 'View 47' },
      { url: 'photos/leopard40-araume-iv/48.jpg', label: 'View 48' },
      { url: 'photos/leopard40-araume-iv/49.jpg', label: 'View 49' },
      { url: 'photos/leopard40-araume-iv/50.jpg', label: 'View 50' },
      { url: 'photos/leopard40-araume-iv/51.jpg', label: 'View 51' },
      { url: 'photos/leopard40-araume-iv/52.jpg', label: 'View 52' },
      { url: 'photos/leopard40-araume-iv/53.jpg', label: 'View 53' },
      { url: 'photos/leopard40-araume-iv/54.jpg', label: 'View 54' },
      { url: 'photos/leopard40-araume-iv/55.jpg', label: 'View 55' },
      { url: 'photos/leopard40-araume-iv/56.jpg', label: 'View 56' },
    ],
    photoCount: 56,
    description:
      'Ex-Moorings Leopard 40 in owner-version 4-cabin configuration. Recently completed world-class refit at the St Lucia base following a comprehensive independent survey. Featuring the modern Simonis & Voogd-designed hull with forward-facing galley, panoramic saloon windows, and large sliding glass doors creating fluid indoor-outdoor living between saloon and aft cockpit. Twin Yanmar 3YM30s with Sail Drive SD20, holding tank, generator, and complete navigation suite. Survey-clean, dock-ready.',
    internalNotes:
      'Moorings has cut twice (-$20K). Local broker indicates seller would entertain $305K cash close. Sea-Tech Marine confirmed surveyor access on 48h notice.',
  },
  {
    id: 'leopard40-ocean-breeze',
    slug: 'ocean-breeze',
    category: '40ft',
    categoryLabel: '40 ft · 3-cabin owner',
    year: 2019,
    make: 'Leopard',
    model: '40',
    name: 'Ocean Breeze',
    headline: 'Ex-Moorings 3-cabin owner version — phase-out complete November 2025, French Polynesia base.',
    loa: '39\' 4"',
    beam: '22\' 1"',
    draft: '4\' 1"',
    cabins: 3,
    heads: 2,
    berths: 6,
    engines: 'Twin Yanmar 3YM30AE — 29 hp ea., Sail Drive SD20',
    engineHours: 2950,
    fuelGal: 95,
    waterGal: 206,
    sails: 'Main + jib + Code-D (factory)',
    electronics: 'Raymarine Axiom · autopilot · Moorings nav suite',
    extras: 'Generator · A/C · solar panels on hard-top bimini · ash white interior · holding tank',
    originatingFleet: 'Moorings (Raiatea)',
    phaseOutDate: '2025-11-04',
    bviAsk: 305700,
    usRetailComp: 555000,
    usComps: [
      { year: 2019, make: 'Leopard', model: '40', priceUSD: 539000, location: 'Miami, FL', source: 'YachtWorld', searchUrl: 'https://www.yachtworld.com/boats-for-sale/type-sail/class-catamaran/make-leopard/model-leopard-40/' },
      { year: 2019, make: 'Leopard', model: '40', priceUSD: 569000, location: 'Newport, RI', source: 'The Multihull Company', searchUrl: 'https://www.multihullcompany.com/sailboats-for-sale/' },
      { year: 2020, make: 'Leopard', model: '40', priceUSD: 599000, location: 'San Diego, CA', source: 'Boat Trader', searchUrl: 'https://www.boattrader.com/sailboats/make-leopard/model-40/' },
    ],
    location: { harbor: 'Uturoa (Raiatea)', country: 'French Polynesia', region: 'Repositioning to Caribbean' },
    destinationPort: 'Fort Lauderdale, FL',
    inspectionWindows: ['Remote video only until Aug 15 (mid-passage)', 'In-person Sep 12 onward at Tortola arrival'],
    remoteVideoAvailable: true,
    sourceBroker: 'Moorings Brokerage',
    sourceListing: 'mooringsbrokerage.com #9851646',
    sourceUrl: 'https://www.mooringsbrokerage.com/used-boats/2019-leopard-40-french-polynesia-ocean-breeze-9851646',
    sourceListed: '2026-01-22',
    sourceLastChecked: '2026-05-18',
    sourcePriceHistory: [
      { date: '2026-01-22', price: 322000 },
      { date: '2026-03-19', price: 305700 },
    ],
    badge: 'Under Deposit',
    status: 'under-deposit',
    daysActive: 116,
    leads: 9,
    inspections: 0,
    photos: [
      { url: 'photos/leopard40-ocean-breeze/1.jpg', label: 'Profile, Polynesia' },
      { url: 'photos/leopard40-ocean-breeze/2.jpg', label: 'Helm station' },
      { url: 'photos/leopard40-ocean-breeze/3.jpg', label: 'Saloon (owner version)' },
      { url: 'photos/leopard40-ocean-breeze/4.jpg', label: 'Owner\'s cabin (3-cabin layout)' },
      { url: 'photos/leopard40-ocean-breeze/5.jpg', label: 'View 5' },
      { url: 'photos/leopard40-ocean-breeze/6.jpg', label: 'View 6' },
      { url: 'photos/leopard40-ocean-breeze/7.jpg', label: 'View 7' },
      { url: 'photos/leopard40-ocean-breeze/8.jpg', label: 'View 8' },
      { url: 'photos/leopard40-ocean-breeze/9.jpg', label: 'View 9' },
      { url: 'photos/leopard40-ocean-breeze/10.jpg', label: 'View 10' },
      { url: 'photos/leopard40-ocean-breeze/11.jpg', label: 'View 11' },
      { url: 'photos/leopard40-ocean-breeze/12.jpg', label: 'View 12' },
      { url: 'photos/leopard40-ocean-breeze/13.jpg', label: 'View 13' },
      { url: 'photos/leopard40-ocean-breeze/14.jpg', label: 'View 14' },
      { url: 'photos/leopard40-ocean-breeze/15.jpg', label: 'View 15' },
      { url: 'photos/leopard40-ocean-breeze/16.jpg', label: 'View 16' },
      { url: 'photos/leopard40-ocean-breeze/17.jpg', label: 'View 17' },
      { url: 'photos/leopard40-ocean-breeze/18.jpg', label: 'View 18' },
      { url: 'photos/leopard40-ocean-breeze/19.jpg', label: 'View 19' },
      { url: 'photos/leopard40-ocean-breeze/20.jpg', label: 'View 20' },
      { url: 'photos/leopard40-ocean-breeze/21.jpg', label: 'View 21' },
      { url: 'photos/leopard40-ocean-breeze/22.jpg', label: 'View 22' },
      { url: 'photos/leopard40-ocean-breeze/23.jpg', label: 'View 23' },
      { url: 'photos/leopard40-ocean-breeze/24.jpg', label: 'View 24' },
      { url: 'photos/leopard40-ocean-breeze/25.jpg', label: 'View 25' },
      { url: 'photos/leopard40-ocean-breeze/26.jpg', label: 'View 26' },
      { url: 'photos/leopard40-ocean-breeze/27.jpg', label: 'View 27' },
      { url: 'photos/leopard40-ocean-breeze/28.jpg', label: 'View 28' },
      { url: 'photos/leopard40-ocean-breeze/29.jpg', label: 'View 29' },
      { url: 'photos/leopard40-ocean-breeze/30.jpg', label: 'View 30' },
      { url: 'photos/leopard40-ocean-breeze/31.jpg', label: 'View 31' },
      { url: 'photos/leopard40-ocean-breeze/32.jpg', label: 'View 32' },
      { url: 'photos/leopard40-ocean-breeze/33.jpg', label: 'View 33' },
      { url: 'photos/leopard40-ocean-breeze/34.jpg', label: 'View 34' },
      { url: 'photos/leopard40-ocean-breeze/35.jpg', label: 'View 35' },
      { url: 'photos/leopard40-ocean-breeze/36.jpg', label: 'View 36' },
      { url: 'photos/leopard40-ocean-breeze/37.jpg', label: 'View 37' },
      { url: 'photos/leopard40-ocean-breeze/38.jpg', label: 'View 38' },
      { url: 'photos/leopard40-ocean-breeze/39.jpg', label: 'View 39' },
      { url: 'photos/leopard40-ocean-breeze/40.jpg', label: 'View 40' },
      { url: 'photos/leopard40-ocean-breeze/41.jpg', label: 'View 41' },
      { url: 'photos/leopard40-ocean-breeze/42.jpg', label: 'View 42' },
      { url: 'photos/leopard40-ocean-breeze/43.jpg', label: 'View 43' },
      { url: 'photos/leopard40-ocean-breeze/44.jpg', label: 'View 44' },
      { url: 'photos/leopard40-ocean-breeze/45.jpg', label: 'View 45' },
      { url: 'photos/leopard40-ocean-breeze/46.jpg', label: 'View 46' },
      { url: 'photos/leopard40-ocean-breeze/47.jpg', label: 'View 47' },
      { url: 'photos/leopard40-ocean-breeze/48.jpg', label: 'View 48' },
      { url: 'photos/leopard40-ocean-breeze/49.jpg', label: 'View 49' },
      { url: 'photos/leopard40-ocean-breeze/50.jpg', label: 'View 50' },
      { url: 'photos/leopard40-ocean-breeze/51.jpg', label: 'View 51' },
      { url: 'photos/leopard40-ocean-breeze/52.jpg', label: 'View 52' },
      { url: 'photos/leopard40-ocean-breeze/53.jpg', label: 'View 53' },
      { url: 'photos/leopard40-ocean-breeze/54.jpg', label: 'View 54' },
      { url: 'photos/leopard40-ocean-breeze/55.jpg', label: 'View 55' },
      { url: 'photos/leopard40-ocean-breeze/56.jpg', label: 'View 56' },
      { url: 'photos/leopard40-ocean-breeze/57.jpg', label: 'View 57' },
      { url: 'photos/leopard40-ocean-breeze/58.jpg', label: 'View 58' },
      { url: 'photos/leopard40-ocean-breeze/59.jpg', label: 'View 59' },
      { url: 'photos/leopard40-ocean-breeze/60.jpg', label: 'View 60' },
      { url: 'photos/leopard40-ocean-breeze/61.jpg', label: 'View 61' },
    ],
    photoCount: 61,
    description:
      'Single-owner 3-cabin Leopard 40 with ash white interior finish, regularly maintained through The Moorings Raiatea charter program. Complete phase-out maintenance executed November 2025 prior to leaving the fleet. Generator, A/C, and solar panels fitted to the hard-top bimini for battery charging. Price includes Papeetized French tax — €260K with tax included. Buyer (Bell, Miami FL) under deposit; close scheduled on Tortola arrival following reposition.',
    internalNotes:
      'Under deposit since 4/14 — buyer wired $30K. Hull arrival in Tortola tracking Sep 12. Insurance binder in place through transit.',
  },
  {
    id: 'leopard40-game-day',
    slug: 'game-day',
    category: '40ft',
    categoryLabel: '40 ft · 3-cabin owner',
    year: 2020,
    make: 'Leopard',
    model: '40',
    name: 'Game Day',
    headline: 'Ex-Moorings 3-cabin owner Leopard 40 in BVI — no storm damage, lighter ash interior.',
    loa: '39\' 4"',
    beam: '21\' 1"',
    draft: '4\' 1"',
    cabins: 3,
    heads: 2,
    berths: 6,
    engines: 'Twin Yanmar 3YM30 AE — 29 hp ea. (2019), Sail Drive SD20',
    engineHours: 2890,
    fuelGal: 95,
    waterGal: 206,
    sails: 'Main + jib (factory rig)',
    electronics: 'Raymarine plotter · autopilot · standard Moorings nav suite',
    extras: 'A/C · generator · Yanmar engines · electric davits · walk-through forward door · lighter ash interior',
    originatingFleet: 'Moorings',
    phaseOutDate: '2025-08-22',
    bviAsk: 319000,
    usRetailComp: 580000,
    usComps: [
      { year: 2020, make: 'Leopard', model: '40', priceUSD: 555000, location: 'Fort Lauderdale, FL', source: 'YachtWorld', searchUrl: 'https://www.yachtworld.com/boats-for-sale/type-sail/class-catamaran/make-leopard/model-leopard-40/' },
      { year: 2020, make: 'Leopard', model: '40', priceUSD: 595000, location: 'Newport, RI', source: 'The Multihull Company', searchUrl: 'https://www.multihullcompany.com/sailboats-for-sale/' },
      { year: 2021, make: 'Leopard', model: '40', priceUSD: 625000, location: 'St. Petersburg, FL', source: 'Boat Trader', searchUrl: 'https://www.boattrader.com/sailboats/make-leopard/model-40/' },
    ],
    location: { harbor: 'Tortola', country: 'Tortola, BVI', region: 'British Virgin Islands' },
    destinationPort: 'Stuart, FL',
    inspectionWindows: ['Jun 14–21', 'Jul 5–12', 'Aug 9–16'],
    remoteVideoAvailable: true,
    sourceBroker: 'Moorings Brokerage',
    sourceListing: 'mooringsbrokerage.com #9425408',
    sourceUrl: 'https://www.mooringsbrokerage.com/used-boats/2020-leopard-40-virgin-islands-british-game-day-9425408',
    sourceListed: '2026-01-15',
    sourceLastChecked: '2026-05-18',
    sourcePriceHistory: [
      { date: '2026-01-15', price: 339000 },
      { date: '2026-04-08', price: 319000 },
    ],
    status: 'available',
    daysActive: 123,
    leads: 8,
    inspections: 0,
    photos: [
      { url: 'photos/leopard40-game-day/1.jpg', label: 'On the hook' },
      { url: 'photos/leopard40-game-day/2.jpg', label: 'Cockpit' },
      { url: 'photos/leopard40-game-day/3.jpg', label: 'Saloon (ash interior)' },
      { url: 'photos/leopard40-game-day/4.jpg', label: 'Owner\'s cabin' },
      { url: 'photos/leopard40-game-day/5.jpg', label: 'View 5' },
      { url: 'photos/leopard40-game-day/6.jpg', label: 'View 6' },
      { url: 'photos/leopard40-game-day/7.jpg', label: 'View 7' },
      { url: 'photos/leopard40-game-day/8.jpg', label: 'View 8' },
      { url: 'photos/leopard40-game-day/9.jpg', label: 'View 9' },
      { url: 'photos/leopard40-game-day/10.jpg', label: 'View 10' },
      { url: 'photos/leopard40-game-day/11.jpg', label: 'View 11' },
      { url: 'photos/leopard40-game-day/12.jpg', label: 'View 12' },
      { url: 'photos/leopard40-game-day/13.jpg', label: 'View 13' },
      { url: 'photos/leopard40-game-day/14.jpg', label: 'View 14' },
      { url: 'photos/leopard40-game-day/15.jpg', label: 'View 15' },
      { url: 'photos/leopard40-game-day/16.jpg', label: 'View 16' },
      { url: 'photos/leopard40-game-day/17.jpg', label: 'View 17' },
      { url: 'photos/leopard40-game-day/18.jpg', label: 'View 18' },
      { url: 'photos/leopard40-game-day/19.jpg', label: 'View 19' },
      { url: 'photos/leopard40-game-day/20.jpg', label: 'View 20' },
      { url: 'photos/leopard40-game-day/21.jpg', label: 'View 21' },
      { url: 'photos/leopard40-game-day/22.jpg', label: 'View 22' },
      { url: 'photos/leopard40-game-day/23.jpg', label: 'View 23' },
      { url: 'photos/leopard40-game-day/24.jpg', label: 'View 24' },
      { url: 'photos/leopard40-game-day/25.jpg', label: 'View 25' },
      { url: 'photos/leopard40-game-day/26.jpg', label: 'View 26' },
      { url: 'photos/leopard40-game-day/27.jpg', label: 'View 27' },
      { url: 'photos/leopard40-game-day/28.jpg', label: 'View 28' },
      { url: 'photos/leopard40-game-day/29.jpg', label: 'View 29' },
      { url: 'photos/leopard40-game-day/30.jpg', label: 'View 30' },
      { url: 'photos/leopard40-game-day/31.jpg', label: 'View 31' },
      { url: 'photos/leopard40-game-day/32.jpg', label: 'View 32' },
      { url: 'photos/leopard40-game-day/33.jpg', label: 'View 33' },
      { url: 'photos/leopard40-game-day/34.jpg', label: 'View 34' },
      { url: 'photos/leopard40-game-day/35.jpg', label: 'View 35' },
      { url: 'photos/leopard40-game-day/36.jpg', label: 'View 36' },
      { url: 'photos/leopard40-game-day/37.jpg', label: 'View 37' },
      { url: 'photos/leopard40-game-day/38.jpg', label: 'View 38' },
      { url: 'photos/leopard40-game-day/39.jpg', label: 'View 39' },
      { url: 'photos/leopard40-game-day/40.jpg', label: 'View 40' },
      { url: 'photos/leopard40-game-day/41.jpg', label: 'View 41' },
      { url: 'photos/leopard40-game-day/42.jpg', label: 'View 42' },
      { url: 'photos/leopard40-game-day/43.jpg', label: 'View 43' },
      { url: 'photos/leopard40-game-day/44.jpg', label: 'View 44' },
      { url: 'photos/leopard40-game-day/45.jpg', label: 'View 45' },
      { url: 'photos/leopard40-game-day/46.jpg', label: 'View 46' },
      { url: 'photos/leopard40-game-day/47.jpg', label: 'View 47' },
      { url: 'photos/leopard40-game-day/48.jpg', label: 'View 48' },
      { url: 'photos/leopard40-game-day/49.jpg', label: 'View 49' },
      { url: 'photos/leopard40-game-day/50.jpg', label: 'View 50' },
      { url: 'photos/leopard40-game-day/51.jpg', label: 'View 51' },
      { url: 'photos/leopard40-game-day/52.jpg', label: 'View 52' },
      { url: 'photos/leopard40-game-day/53.jpg', label: 'View 53' },
      { url: 'photos/leopard40-game-day/54.jpg', label: 'View 54' },
      { url: 'photos/leopard40-game-day/55.jpg', label: 'View 55' },
      { url: 'photos/leopard40-game-day/56.jpg', label: 'View 56' },
      { url: 'photos/leopard40-game-day/57.jpg', label: 'View 57' },
      { url: 'photos/leopard40-game-day/58.jpg', label: 'View 58' },
      { url: 'photos/leopard40-game-day/59.jpg', label: 'View 59' },
      { url: 'photos/leopard40-game-day/60.jpg', label: 'View 60' },
      { url: 'photos/leopard40-game-day/61.jpg', label: 'View 61' },
      { url: 'photos/leopard40-game-day/62.jpg', label: 'View 62' },
      { url: 'photos/leopard40-game-day/63.jpg', label: 'View 63' },
      { url: 'photos/leopard40-game-day/64.jpg', label: 'View 64' },
      { url: 'photos/leopard40-game-day/65.jpg', label: 'View 65' },
    ],
    photoCount: 65,
    description:
      'Newer ex-Moorings 3-cabin owner-version Leopard 40 with the lighter ash interior. Modern Simonis & Voogd design with forward-facing galley and panoramic saloon. No storm damage history. Equipped with air conditioning, generator, Yanmar engines, electric davits, and walk-through forward door. Available with phase-out OR as-is/where-is.',
    internalNotes:
      'Recent $20K price cut. Seller open to as-is/where-is which removes phase-out lead time. Strong candidate for fast-close buyer.',
  },
  {
    id: 'leopard45-kokamo',
    slug: 'kokamo',
    category: '45ft',
    categoryLabel: '45 ft · 4-cabin crewed-spec',
    year: 2020,
    make: 'Leopard',
    model: '45',
    name: 'Kokamo',
    headline: 'Rare crewed-version Leopard 45 with upgraded spec — reduced usage from Covid years.',
    loa: '45\' 0"',
    beam: '24\' 2"',
    draft: '4\' 11"',
    cabins: 4,
    heads: 5,
    berths: 10,
    engines: 'Twin Yanmar 4JH45 — 45 hp ea. (2019), SD60 saildrives',
    engineHours: 1273,
    fuelGal: 91,
    waterGal: 103,
    sails: 'Ullman fully battened main · roller-furling genoa · electric Lewmar winches',
    electronics: 'Raymarine full suite · autopilot · ADS-B AIS',
    extras: 'Northern Lights 9 kW genset · Sea Recovery watermaker · flexi teak cockpit · cockpit refrigerator · inverter · 2× Cruisair 16K BTU A/C · 2× 100W solar · hardtop bimini',
    originatingFleet: 'Moorings (crewed program)',
    phaseOutDate: '2024-12-08',
    bviAsk: 419000,
    usRetailComp: 725000,
    usComps: [
      { year: 2019, make: 'Leopard', model: '45', priceUSD: 695000, location: 'Miami, FL', source: 'YachtWorld', searchUrl: 'https://www.yachtworld.com/boats-for-sale/type-sail/class-catamaran/make-leopard/model-leopard-45/' },
      { year: 2020, make: 'Leopard', model: '45', priceUSD: 745000, location: 'Charleston, SC', source: 'The Multihull Company', searchUrl: 'https://www.multihullcompany.com/sailboats-for-sale/' },
      { year: 2020, make: 'Leopard', model: '45', priceUSD: 765000, location: 'Newport, RI', source: 'Boat Trader', searchUrl: 'https://www.boattrader.com/sailboats/make-leopard/model-45/' },
    ],
    location: { harbor: 'Tortola', country: 'Tortola, BVI', region: 'British Virgin Islands' },
    destinationPort: 'Stuart, FL',
    inspectionWindows: ['May 31–Jun 7', 'Jun 21–28', 'Jul 12–19'],
    remoteVideoAvailable: true,
    sourceBroker: 'Moorings Brokerage',
    sourceListing: 'mooringsbrokerage.com #9478689',
    sourceUrl: 'https://www.mooringsbrokerage.com/used-boats/2020-leopard-45-virgin-islands-british-kokamo-9478689',
    sourceListed: '2025-12-14',
    sourceLastChecked: '2026-05-18',
    sourcePriceHistory: [
      { date: '2025-12-14', price: 449000 },
      { date: '2026-03-01', price: 419000 },
    ],
    badge: 'Featured',
    status: 'inspection-scheduled',
    daysActive: 156,
    inspections: 2,
    leads: 22,
    photos: [
      { url: 'photos/leopard45-kokamo/1.jpg', label: 'Under sail' },
      { url: 'photos/leopard45-kokamo/2.jpg', label: 'Flybridge helm' },
      { url: 'photos/leopard45-kokamo/3.jpg', label: 'Saloon & galley' },
      { url: 'photos/leopard45-kokamo/4.jpg', label: 'Master cabin' },
      { url: 'photos/leopard45-kokamo/5.jpg', label: 'View 5' },
      { url: 'photos/leopard45-kokamo/6.jpg', label: 'View 6' },
      { url: 'photos/leopard45-kokamo/7.jpg', label: 'View 7' },
      { url: 'photos/leopard45-kokamo/8.jpg', label: 'View 8' },
      { url: 'photos/leopard45-kokamo/9.jpg', label: 'View 9' },
      { url: 'photos/leopard45-kokamo/10.jpg', label: 'View 10' },
      { url: 'photos/leopard45-kokamo/11.jpg', label: 'View 11' },
      { url: 'photos/leopard45-kokamo/12.jpg', label: 'View 12' },
      { url: 'photos/leopard45-kokamo/13.jpg', label: 'View 13' },
      { url: 'photos/leopard45-kokamo/14.jpg', label: 'View 14' },
      { url: 'photos/leopard45-kokamo/15.jpg', label: 'View 15' },
      { url: 'photos/leopard45-kokamo/16.jpg', label: 'View 16' },
      { url: 'photos/leopard45-kokamo/17.jpg', label: 'View 17' },
      { url: 'photos/leopard45-kokamo/18.jpg', label: 'View 18' },
      { url: 'photos/leopard45-kokamo/19.jpg', label: 'View 19' },
      { url: 'photos/leopard45-kokamo/20.jpg', label: 'View 20' },
      { url: 'photos/leopard45-kokamo/21.jpg', label: 'View 21' },
      { url: 'photos/leopard45-kokamo/22.jpg', label: 'View 22' },
      { url: 'photos/leopard45-kokamo/23.jpg', label: 'View 23' },
      { url: 'photos/leopard45-kokamo/24.jpg', label: 'View 24' },
      { url: 'photos/leopard45-kokamo/25.jpg', label: 'View 25' },
      { url: 'photos/leopard45-kokamo/26.jpg', label: 'View 26' },
      { url: 'photos/leopard45-kokamo/27.jpg', label: 'View 27' },
      { url: 'photos/leopard45-kokamo/28.jpg', label: 'View 28' },
      { url: 'photos/leopard45-kokamo/29.jpg', label: 'View 29' },
      { url: 'photos/leopard45-kokamo/30.jpg', label: 'View 30' },
      { url: 'photos/leopard45-kokamo/31.jpg', label: 'View 31' },
      { url: 'photos/leopard45-kokamo/32.jpg', label: 'View 32' },
      { url: 'photos/leopard45-kokamo/33.jpg', label: 'View 33' },
      { url: 'photos/leopard45-kokamo/34.jpg', label: 'View 34' },
      { url: 'photos/leopard45-kokamo/35.jpg', label: 'View 35' },
      { url: 'photos/leopard45-kokamo/36.jpg', label: 'View 36' },
      { url: 'photos/leopard45-kokamo/37.jpg', label: 'View 37' },
      { url: 'photos/leopard45-kokamo/38.jpg', label: 'View 38' },
      { url: 'photos/leopard45-kokamo/39.jpg', label: 'View 39' },
      { url: 'photos/leopard45-kokamo/40.jpg', label: 'View 40' },
      { url: 'photos/leopard45-kokamo/41.jpg', label: 'View 41' },
      { url: 'photos/leopard45-kokamo/42.jpg', label: 'View 42' },
      { url: 'photos/leopard45-kokamo/43.jpg', label: 'View 43' },
      { url: 'photos/leopard45-kokamo/44.jpg', label: 'View 44' },
      { url: 'photos/leopard45-kokamo/45.jpg', label: 'View 45' },
      { url: 'photos/leopard45-kokamo/46.jpg', label: 'View 46' },
      { url: 'photos/leopard45-kokamo/47.jpg', label: 'View 47' },
      { url: 'photos/leopard45-kokamo/48.jpg', label: 'View 48' },
      { url: 'photos/leopard45-kokamo/49.jpg', label: 'View 49' },
      { url: 'photos/leopard45-kokamo/50.jpg', label: 'View 50' },
      { url: 'photos/leopard45-kokamo/51.jpg', label: 'View 51' },
      { url: 'photos/leopard45-kokamo/52.jpg', label: 'View 52' },
      { url: 'photos/leopard45-kokamo/53.jpg', label: 'View 53' },
      { url: 'photos/leopard45-kokamo/54.jpg', label: 'View 54' },
      { url: 'photos/leopard45-kokamo/55.jpg', label: 'View 55' },
      { url: 'photos/leopard45-kokamo/56.jpg', label: 'View 56' },
      { url: 'photos/leopard45-kokamo/57.jpg', label: 'View 57' },
      { url: 'photos/leopard45-kokamo/58.jpg', label: 'View 58' },
      { url: 'photos/leopard45-kokamo/59.jpg', label: 'View 59' },
      { url: 'photos/leopard45-kokamo/60.jpg', label: 'View 60' },
      { url: 'photos/leopard45-kokamo/61.jpg', label: 'View 61' },
      { url: 'photos/leopard45-kokamo/62.jpg', label: 'View 62' },
      { url: 'photos/leopard45-kokamo/63.jpg', label: 'View 63' },
      { url: 'photos/leopard45-kokamo/64.jpg', label: 'View 64' },
      { url: 'photos/leopard45-kokamo/65.jpg', label: 'View 65' },
      { url: 'photos/leopard45-kokamo/66.jpg', label: 'View 66' },
      { url: 'photos/leopard45-kokamo/67.jpg', label: 'View 67' },
      { url: 'photos/leopard45-kokamo/68.jpg', label: 'View 68' },
      { url: 'photos/leopard45-kokamo/69.jpg', label: 'View 69' },
      { url: 'photos/leopard45-kokamo/70.jpg', label: 'View 70' },
      { url: 'photos/leopard45-kokamo/71.jpg', label: 'View 71' },
      { url: 'photos/leopard45-kokamo/72.jpg', label: 'View 72' },
      { url: 'photos/leopard45-kokamo/73.jpg', label: 'View 73' },
    ],
    photoCount: 73,
    description:
      'Rare crewed-version Leopard 45 with upgraded specification throughout — only 1,273 engine hours due to reduced usage during Covid years. Notable upgrades include flexi teak in cockpits, cockpit refrigerator, watermaker, inverter, and 2× Cruisair 16K BTU air conditioning. Northern Lights 9kW generator, Sea Recovery watermaker, dual 100W solar panels, hardtop bimini. Ullman fully-battened mainsail with electric Lewmar primary winches and roller-furling genoa.',
    internalNotes:
      'Best margin/effort ratio in current inventory at $106K gross at 20% duty. Two inspections pending (Whitman 5/31, Royce 6/21). Hold price at $419K — broker confirmed seller firm above $410K.',
  },
  {
    id: 'leopard45-soul-rebel',
    slug: 'soul-rebel',
    category: '45ft',
    categoryLabel: '45 ft · 4-cabin + crew',
    year: 2019,
    make: 'Leopard',
    model: '45',
    name: 'Soul Rebel',
    headline: 'Single-owner ex-Moorings Leopard 45, lithium-ready, Raymarine Axiom suite.',
    loa: '45\' 0"',
    beam: '24\' 1"',
    draft: '4\' 11"',
    cabins: 4,
    heads: 4,
    berths: 10,
    engines: 'Twin Yanmar 4JH45C — 45 hp ea., saildrives',
    engineHours: 2800,
    fuelGal: 185,
    waterGal: 206,
    sails: 'Stackpack lazyjack main · furling headsail · electric Lewmar primary winches',
    electronics: 'Raymarine Axiom 9 · autopilot · navigation suite',
    extras: 'Northern Lights 9 kW genset · Sea Recovery 117 L/hr watermaker · 630 Ah house battery · Corian galley · Vitrifrigo 2-drawer fridge/freezer · mainsheet bridle · crew cabin',
    originatingFleet: 'Moorings',
    phaseOutDate: '2024-05-30',
    bviAsk: 355000,
    usRetailComp: 675000,
    usComps: [
      { year: 2019, make: 'Leopard', model: '45', priceUSD: 649000, location: 'Fort Lauderdale, FL', source: 'YachtWorld', searchUrl: 'https://www.yachtworld.com/boats-for-sale/type-sail/class-catamaran/make-leopard/model-leopard-45/' },
      { year: 2019, make: 'Leopard', model: '45', priceUSD: 685000, location: 'Annapolis, MD', source: 'The Multihull Company', searchUrl: 'https://www.multihullcompany.com/sailboats-for-sale/' },
      { year: 2020, make: 'Leopard', model: '45', priceUSD: 705000, location: 'St. Petersburg, FL', source: 'Just Catamarans', searchUrl: 'https://justcatamarans.net/listings/' },
    ],
    location: { harbor: 'Virgin Gorda', country: 'BVI', region: 'British Virgin Islands' },
    destinationPort: 'Fort Lauderdale, FL',
    inspectionWindows: ['May 31–Jun 7', 'Jun 21–28', 'Jul 19–26'],
    remoteVideoAvailable: true,
    sourceBroker: 'BVI Yacht Sales',
    sourceListing: 'bviyachtsales.com #2848720',
    sourceUrl: 'https://bviyachtsales.com/yacht/2848720/2019-Robertson&Caine-45-Leopard-SoulRebel',
    sourceListed: '2024-09-10',
    sourceLastChecked: '2026-05-18',
    sourcePriceHistory: [
      { date: '2024-09-10', price: 399000 },
      { date: '2025-04-22', price: 379000 },
      { date: '2025-11-04', price: 365000 },
      { date: '2026-03-15', price: 355000 },
    ],
    badge: 'Widest Spread',
    status: 'available',
    daysActive: 615,
    leads: 19,
    inspections: 1,
    photos: [
      { url: 'photos/leopard45-soul-rebel/1.jpg', label: 'Profile, Virgin Gorda' },
      { url: 'photos/leopard45-soul-rebel/2.jpg', label: 'Cockpit & helm' },
      { url: 'photos/leopard45-soul-rebel/3.jpg', label: 'Saloon' },
      { url: 'photos/leopard45-soul-rebel/4.jpg', label: 'Master cabin' },
    ],
    photoCount: 4,
    description:
      'Single-owner 2019 Leopard 45 in 4-cabin + crew cabin configuration, primary Moorings charter service Jan 2019 - May 2024, then transferred out of charter for handover work mid-2024 and lightly used since. Twin Yanmar 45HP engines with saildrives, Northern Lights 9kW generator, Sea Recovery 117 L/hr watermaker, 630Ah house bank, Raymarine Axiom 9 navigation suite. Large galley with Corian countertops and Vitrifrigo 2-drawer fridge/freezer. Stackpack lazyjack, mainsheet bridle, furling headsail. Routine maintenance only since charter exit.',
    internalNotes:
      'Three price cuts (-$44K total) since Sep 2024. Seller motivated — extended dockage exposure. Highest buyer-savings opportunity in current inventory at $135K vs comp.',
  },
  {
    id: 'lagoon450f-miss-summer',
    slug: 'miss-summer',
    category: '45ft',
    categoryLabel: '45 ft · 4-cabin + crew',
    year: 2014,
    make: 'Lagoon',
    model: '450F',
    name: 'Miss Summer',
    headline: 'Heavily refit 2014 Lagoon 450F — 1200Ah lithium, 600W solar, 2022 standing rigging. Survey passed with NO recommendations.',
    loa: '45\' 0"',
    beam: '25\' 10"',
    draft: '4\' 3"',
    cabins: 4,
    heads: 4,
    berths: 12,
    engines: 'Twin Yanmar 4JH5E — 54 hp ea., SD60 saildrives (replaced 2022), 3-blade fixed Volvo props (2021)',
    engineHours: 3000,
    fuelGal: 275,
    waterGal: 185,
    sails: '2022 standing rigging · refreshed canvas',
    electronics: 'Mastervolt inverter/charger · Raymarine navigation',
    extras: 'Cummins Onan 13.5 kW genset · 1200 Ah lithium bank · 600W solar · Micro-Air EasyStarts · 2 cabin AC overnight off-grid · high-output watermaker · refreshed upholstery & canvas · 4× 175L water tanks',
    originatingFleet: 'Private owner (refit-focused)',
    phaseOutDate: null,
    bviAsk: 445000,
    usRetailComp: 725000,
    usComps: [
      { year: 2014, make: 'Lagoon', model: '450', priceUSD: 525000, location: 'Tampa, FL', source: 'YachtWorld', searchUrl: 'https://www.yachtworld.com/boats-for-sale/type-sail/class-catamaran/make-lagoon/model-lagoon-450/' },
      { year: 2015, make: 'Lagoon', model: '450', priceUSD: 625000, location: 'San Diego, CA', source: 'The Multihull Company', searchUrl: 'https://www.multihullcompany.com/sailboats-for-sale/' },
      { year: 2015, make: 'Lagoon', model: '450 (lithium refit)', priceUSD: 745000, location: 'Annapolis, MD', source: 'YachtWorld', searchUrl: 'https://www.yachtworld.com/boats-for-sale/type-sail/class-catamaran/make-lagoon/' },
    ],
    location: { harbor: 'Nanny Cay', country: 'Tortola, BVI', region: 'British Virgin Islands' },
    destinationPort: 'Tampa, FL',
    inspectionWindows: ['Jun 7–14', 'Jul 5–12', 'Aug 23–30'],
    remoteVideoAvailable: true,
    sourceBroker: 'BVI Yacht Sales',
    sourceListing: 'bviyachtsales.com #2847342',
    sourceUrl: 'https://bviyachtsales.com/yacht/2847342/2014-Lagoon-45-450F-MissSummer',
    sourceListed: '2025-11-30',
    sourceLastChecked: '2026-05-18',
    sourcePriceHistory: [
      { date: '2025-11-30', price: 479000 },
      { date: '2026-02-15', price: 459000 },
      { date: '2026-04-20', price: 445000 },
    ],
    badge: 'Off-Grid Ready',
    status: 'available',
    daysActive: 170,
    leads: 11,
    inspections: 0,
    photos: [
      { url: 'photos/lagoon450f-miss-summer/1.jpg', label: 'Profile, Nanny Cay' },
      { url: 'photos/lagoon450f-miss-summer/2.jpg', label: 'Cockpit' },
      { url: 'photos/lagoon450f-miss-summer/3.jpg', label: 'Saloon (lithium-quiet)' },
      { url: 'photos/lagoon450f-miss-summer/4.jpg', label: 'Master cabin' },
    ],
    photoCount: 4,
    description:
      'Although Miss Summer is a 2014 model, nothing about this yacht reflects her age. Exceptional level of refit including 1200Ah lithium house bank, Mastervolt inverter/charger suite, 600W solar, Micro-Air EasyStarts delivering true off-grid capability — silent nights on lithium power with one to two air-conditioning units overnight, no generator required. 2022 standing rigging, SD60 saildrives, refreshed upholstery and canvas. Cummins Onan 13.5kW generator, high-output watermaker. Most recent survey passed with NO recommendations.',
    internalNotes:
      'Premium refit positioning supports higher retail comp ($725K). Margin tighter than other inventory but appeals to off-grid liveaboard buyer profile. Survey-clean.',
  },
  {
    id: 'lagoon42-frost-free',
    slug: 'frost-free',
    category: '40ft',
    categoryLabel: '42 ft · 4-cabin',
    year: 2020,
    make: 'Lagoon',
    model: '42',
    name: 'Frost Free',
    headline: 'Released from Moorings charter with minimal Covid-era usage — upgraded Northern Lights generator + Sea Recovery watermaker.',
    loa: '42\' 0"',
    beam: '25\' 3"',
    draft: '4\' 1"',
    cabins: 4,
    heads: 4,
    berths: 8,
    engines: 'Twin Yanmar 4JH45 — 45 hp ea., 3-blade aluminum props',
    engineHours: 1850,
    fuelGal: 158,
    waterGal: 185,
    sails: 'Main + self-tacking jib (factory rig)',
    electronics: 'B&G chart plotter · autopilot · Moorings nav suite',
    extras: 'Northern Lights 6 kW genset · Sea Recovery watermaker · A/C · galley fully equipped · extensive nav electronics',
    originatingFleet: 'Moorings',
    phaseOutDate: '2025-09-18',
    bviAsk: 329000,
    usRetailComp: 585000,
    usComps: [
      { year: 2019, make: 'Lagoon', model: '42', priceUSD: 549000, location: 'Fort Lauderdale, FL', source: 'YachtWorld', searchUrl: 'https://www.yachtworld.com/boats-for-sale/type-sail/class-catamaran/make-lagoon/model-lagoon-42/' },
      { year: 2020, make: 'Lagoon', model: '42', priceUSD: 595000, location: 'Annapolis, MD', source: 'The Multihull Company', searchUrl: 'https://www.multihullcompany.com/sailboats-for-sale/' },
      { year: 2020, make: 'Lagoon', model: '42', priceUSD: 619000, location: 'Newport, RI', source: 'Just Catamarans', searchUrl: 'https://justcatamarans.net/listings/' },
    ],
    location: { harbor: 'Marigot', country: 'Saint Martin (French)', region: 'Northern Caribbean' },
    destinationPort: 'Fort Lauderdale, FL',
    inspectionWindows: ['Jun 21–28', 'Jul 26–Aug 2', 'Sep 6–13'],
    remoteVideoAvailable: true,
    sourceBroker: 'Moorings Brokerage',
    sourceListing: 'mooringsbrokerage.com #9955610',
    sourceUrl: 'https://www.mooringsbrokerage.com/used-boats/2020-lagoon-42-virgin-islands-british-frost-free-9955610',
    sourceListed: '2026-03-11',
    sourceLastChecked: '2026-05-18',
    sourcePriceHistory: [{ date: '2026-03-11', price: 329000 }],
    status: 'available',
    daysActive: 68,
    leads: 8,
    inspections: 0,
    photos: [
      { url: 'photos/lagoon42-frost-free/1.jpg', label: 'Profile' },
      { url: 'photos/lagoon42-frost-free/2.jpg', label: 'Cockpit' },
      { url: 'photos/lagoon42-frost-free/3.jpg', label: 'Saloon' },
      { url: 'photos/lagoon42-frost-free/4.jpg', label: 'Cabin' },
      { url: 'photos/lagoon42-frost-free/5.jpg', label: 'View 5' },
      { url: 'photos/lagoon42-frost-free/6.jpg', label: 'View 6' },
      { url: 'photos/lagoon42-frost-free/7.jpg', label: 'View 7' },
      { url: 'photos/lagoon42-frost-free/8.jpg', label: 'View 8' },
      { url: 'photos/lagoon42-frost-free/9.jpg', label: 'View 9' },
      { url: 'photos/lagoon42-frost-free/10.jpg', label: 'View 10' },
      { url: 'photos/lagoon42-frost-free/11.jpg', label: 'View 11' },
      { url: 'photos/lagoon42-frost-free/12.jpg', label: 'View 12' },
      { url: 'photos/lagoon42-frost-free/13.jpg', label: 'View 13' },
      { url: 'photos/lagoon42-frost-free/14.jpg', label: 'View 14' },
      { url: 'photos/lagoon42-frost-free/15.jpg', label: 'View 15' },
      { url: 'photos/lagoon42-frost-free/16.jpg', label: 'View 16' },
      { url: 'photos/lagoon42-frost-free/17.jpg', label: 'View 17' },
      { url: 'photos/lagoon42-frost-free/18.jpg', label: 'View 18' },
      { url: 'photos/lagoon42-frost-free/19.jpg', label: 'View 19' },
      { url: 'photos/lagoon42-frost-free/20.jpg', label: 'View 20' },
      { url: 'photos/lagoon42-frost-free/21.jpg', label: 'View 21' },
      { url: 'photos/lagoon42-frost-free/22.jpg', label: 'View 22' },
      { url: 'photos/lagoon42-frost-free/23.jpg', label: 'View 23' },
      { url: 'photos/lagoon42-frost-free/24.jpg', label: 'View 24' },
      { url: 'photos/lagoon42-frost-free/25.jpg', label: 'View 25' },
      { url: 'photos/lagoon42-frost-free/26.jpg', label: 'View 26' },
      { url: 'photos/lagoon42-frost-free/27.jpg', label: 'View 27' },
      { url: 'photos/lagoon42-frost-free/28.jpg', label: 'View 28' },
      { url: 'photos/lagoon42-frost-free/29.jpg', label: 'View 29' },
      { url: 'photos/lagoon42-frost-free/30.jpg', label: 'View 30' },
      { url: 'photos/lagoon42-frost-free/31.jpg', label: 'View 31' },
      { url: 'photos/lagoon42-frost-free/32.jpg', label: 'View 32' },
      { url: 'photos/lagoon42-frost-free/33.jpg', label: 'View 33' },
      { url: 'photos/lagoon42-frost-free/34.jpg', label: 'View 34' },
      { url: 'photos/lagoon42-frost-free/35.jpg', label: 'View 35' },
      { url: 'photos/lagoon42-frost-free/36.jpg', label: 'View 36' },
      { url: 'photos/lagoon42-frost-free/37.jpg', label: 'View 37' },
      { url: 'photos/lagoon42-frost-free/38.jpg', label: 'View 38' },
      { url: 'photos/lagoon42-frost-free/39.jpg', label: 'View 39' },
      { url: 'photos/lagoon42-frost-free/40.jpg', label: 'View 40' },
      { url: 'photos/lagoon42-frost-free/41.jpg', label: 'View 41' },
      { url: 'photos/lagoon42-frost-free/42.jpg', label: 'View 42' },
      { url: 'photos/lagoon42-frost-free/43.jpg', label: 'View 43' },
      { url: 'photos/lagoon42-frost-free/44.jpg', label: 'View 44' },
      { url: 'photos/lagoon42-frost-free/45.jpg', label: 'View 45' },
      { url: 'photos/lagoon42-frost-free/46.jpg', label: 'View 46' },
      { url: 'photos/lagoon42-frost-free/47.jpg', label: 'View 47' },
      { url: 'photos/lagoon42-frost-free/48.jpg', label: 'View 48' },
      { url: 'photos/lagoon42-frost-free/49.jpg', label: 'View 49' },
      { url: 'photos/lagoon42-frost-free/50.jpg', label: 'View 50' },
      { url: 'photos/lagoon42-frost-free/51.jpg', label: 'View 51' },
      { url: 'photos/lagoon42-frost-free/52.jpg', label: 'View 52' },
      { url: 'photos/lagoon42-frost-free/53.jpg', label: 'View 53' },
      { url: 'photos/lagoon42-frost-free/54.jpg', label: 'View 54' },
      { url: 'photos/lagoon42-frost-free/55.jpg', label: 'View 55' },
      { url: 'photos/lagoon42-frost-free/56.jpg', label: 'View 56' },
      { url: 'photos/lagoon42-frost-free/57.jpg', label: 'View 57' },
      { url: 'photos/lagoon42-frost-free/58.jpg', label: 'View 58' },
      { url: 'photos/lagoon42-frost-free/59.jpg', label: 'View 59' },
      { url: 'photos/lagoon42-frost-free/60.jpg', label: 'View 60' },
      { url: 'photos/lagoon42-frost-free/61.jpg', label: 'View 61' },
      { url: 'photos/lagoon42-frost-free/62.jpg', label: 'View 62' },
    ],
    photoCount: 62,
    description:
      'Released from the Moorings charter fleet with minimal usage during the Covid period — only 1,850 engine hours on a 2020-model hull. Notable upgrades include Northern Lights 6kW generator and Sea Recovery watermaker. Well-spec\'d throughout with extensive galley equipment and navigation electronics. B&G chart plotter, autopilot, complete Moorings nav suite. Twin Yanmar 4JH45s with 3-blade aluminum props.',
    internalNotes:
      'Just listed — no source price movement yet. Saint Martin location (French side) is European-VAT-not-paid which simplifies our offshore-export documentation. Photo set on source is light at 8 shots.',
  },
  {
    id: 'bali45-four-sevens',
    slug: 'four-sevens',
    category: '45ft',
    categoryLabel: '45 ft · 3-cabin owner',
    year: 2015,
    make: 'Bali',
    model: '4.5',
    name: 'Four Sevens',
    headline: 'Solar + lithium 2015 Bali 4.5 — generous owner version, Grenada-based, ready for cruising or liveaboard.',
    loa: '45\' 0"',
    beam: '24\' 7"',
    draft: '4\' 5"',
    cabins: 3,
    heads: 3,
    berths: 8,
    engines: 'Twin Nanni diesel — 50 hp ea. (100 hp total)',
    engineHours: 3200,
    fuelGal: 158,
    waterGal: 211,
    sails: 'Main + self-tacking jib (Bali signature folding aft door layout)',
    electronics: 'Raymarine plotter · autopilot · radar',
    extras: 'Solar panel array · lithium house bank · generator · large refrigerator/freezer · 48" smart TV · expansive viewing windows · spacious storage · folding garage door',
    originatingFleet: 'Private owner',
    phaseOutDate: null,
    bviAsk: 449000,
    usRetailComp: 735000,
    usComps: [
      { year: 2015, make: 'Bali', model: '4.5', priceUSD: 695000, location: 'Tampa, FL', source: 'YachtWorld', searchUrl: 'https://www.yachtworld.com/boats-for-sale/type-sail/class-catamaran/make-bali/model-bali-4-5/' },
      { year: 2016, make: 'Bali', model: '4.5', priceUSD: 749000, location: 'San Diego, CA', source: 'The Multihull Company', searchUrl: 'https://www.multihullcompany.com/sailboats-for-sale/' },
      { year: 2015, make: 'Bali', model: '4.5', priceUSD: 765000, location: 'Fort Lauderdale, FL', source: 'Just Catamarans', searchUrl: 'https://justcatamarans.net/listings/' },
    ],
    location: { harbor: 'St. Georges', country: 'Grenada', region: 'Southern Caribbean' },
    destinationPort: 'Tampa, FL',
    inspectionWindows: ['Jun 14–28', 'Jul 19–Aug 9 (extended window)', 'Nov 8–22'],
    remoteVideoAvailable: true,
    sourceBroker: 'Just Catamarans',
    sourceListing: 'justcatamarans.net/bali-4-5-four-sevens',
    sourceUrl: 'https://justcatamarans.net/catamaran-listing/bali-4-5-four-sevens/',
    sourceListed: '2025-08-14',
    sourceLastChecked: '2026-05-18',
    sourcePriceHistory: [
      { date: '2025-08-14', price: 489000 },
      { date: '2025-12-02', price: 469000 },
      { date: '2026-03-30', price: 449000 },
    ],
    badge: 'Liveaboard Ready',
    status: 'inquiry',
    daysActive: 277,
    leads: 7,
    inspections: 0,
    photos: [
      { url: 'photos/bali45-four-sevens/1.jpg', label: 'Profile, Grenada' },
      { url: 'photos/bali45-four-sevens/2.jpg', label: 'Flybridge' },
      { url: 'photos/bali45-four-sevens/3.jpg', label: 'Saloon (open concept)' },
      { url: 'photos/bali45-four-sevens/4.jpg', label: 'Owner\'s cabin' },
      { url: 'photos/bali45-four-sevens/5.jpg', label: 'View 5' },
      { url: 'photos/bali45-four-sevens/6.jpg', label: 'View 6' },
      { url: 'photos/bali45-four-sevens/7.jpg', label: 'View 7' },
      { url: 'photos/bali45-four-sevens/8.jpg', label: 'View 8' },
      { url: 'photos/bali45-four-sevens/9.jpg', label: 'View 9' },
      { url: 'photos/bali45-four-sevens/10.jpg', label: 'View 10' },
      { url: 'photos/bali45-four-sevens/11.jpg', label: 'View 11' },
      { url: 'photos/bali45-four-sevens/12.jpg', label: 'View 12' },
      { url: 'photos/bali45-four-sevens/13.jpg', label: 'View 13' },
      { url: 'photos/bali45-four-sevens/14.jpg', label: 'View 14' },
      { url: 'photos/bali45-four-sevens/15.jpg', label: 'View 15' },
      { url: 'photos/bali45-four-sevens/16.jpg', label: 'View 16' },
      { url: 'photos/bali45-four-sevens/17.jpg', label: 'View 17' },
      { url: 'photos/bali45-four-sevens/18.jpg', label: 'View 18' },
      { url: 'photos/bali45-four-sevens/19.jpg', label: 'View 19' },
      { url: 'photos/bali45-four-sevens/20.jpg', label: 'View 20' },
      { url: 'photos/bali45-four-sevens/21.jpg', label: 'View 21' },
      { url: 'photos/bali45-four-sevens/22.jpg', label: 'View 22' },
    ],
    photoCount: 22,
    description:
      'Owner-version Bali 4.5 with the signature folding aft door layout (saloon opens fully to cockpit, single indoor-outdoor living space). Equipped for cruising or liveaboard: solar panel array, lithium house bank, generator, large refrigerator/freezer, 48" smart TV, expansive viewing windows. Twin Nanni 50hp diesels. Three-cabin owner version with three heads. Currently at Port Louis Marina, Grenada.',
    internalNotes:
      'Three price cuts (-$40K total) since Aug 2025. Grenada delivery adds 2-3 days vs BVI departure but customs paperwork identical. Hennessey Group (Sarasota, FL) inquiry from 5/11 — inspection booking pending.',
  },
];


// ============================== Helpers ==============================

function findBoat(id) {
  return BOATS.find((b) => b.id === id);
}

function statusLabel(s) {
  return {
    'available': 'Available',
    'inquiry': 'Inquiry Live',
    'inspection-scheduled': 'Inspection Scheduled',
    'under-deposit': 'Under Deposit',
    'under-delivery': 'Under Delivery',
    'closed': 'Closed',
  }[s] || s;
}

function fmtUSD(n) {
  if (n === null || n === undefined) return '—';
  return '$' + Math.round(n).toLocaleString('en-US');
}
function fmtUSDShort(n) {
  if (n === null || n === undefined) return '—';
  if (Math.abs(n) >= 1_000_000) return '$' + (n / 1_000_000).toFixed(2) + 'M';
  if (Math.abs(n) >= 1_000) return '$' + Math.round(n / 1_000) + 'K';
  return '$' + n;
}
function fmtPct(n, digits = 0) {
  if (n === null || n === undefined) return '—';
  return (n * 100).toFixed(digits) + '%';
}
function fmtNum(n) {
  if (n === null || n === undefined) return '—';
  return n.toLocaleString('en-US');
}
function fmtDate(s) {
  if (!s) return '—';
  const d = new Date(s);
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

// CommonJS export — only fires under Node (watermark.js, scraper.js).
// Browsers ignore this block because `module` is undefined.
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { SETTINGS, BOATS, HERO_PHOTO };
}
